[tool.poetry]
name = "smolmodels"
version = "0.1.0"
description = ""
authors = [
    "marcellodebernardi <marcello.debernardi@outlook.com>",
    "vaibs-d <vaibhavatlamarts@gmail.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.0"
google-generativeai = "^0.8.2"
imbalanced-learn = "^0.12.4"
pydantic = "^2.9.2"
scikit-learn = "^1.5.2"
seaborn = "^0.12.2"
aisuite = {extras = ["all"], version = "^0.1.7"}


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
black = "^24.10.0"
pre-commit = "^4.0.1"
ruff = "^0.9.1"
jupyterlab = "^4.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py312"]
exclude = '''
/(
    \.git
  | \.venv
  | __pycache__
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "E203",  # Whitespace before ':'
    "E501",  # Line length
    "E402",  # Imports not at top of file
]