name: plexe

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - smolcache:/app/.smolcache
    depends_on:
      - redis
      - mongodb
    networks:
      - plexe-network

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file: .env
    volumes:
      - smolcache:/app/.smolcache
    depends_on:
      - redis
      - mongodb
    networks:
      - plexe-network

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - plexe-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - plexe-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - plexe-network

networks:
  plexe-network:
    driver: bridge

volumes:
  smolcache:
    driver: local
  redis_data:
    driver: local
  mongodb_data:
    driver: local
